from sqlalchemy import Column, String, DateTime, Text, JSON, Integer, ForeignKey, Boolean, Float
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid
from typing import Optional, Dict, Any

Base = declarative_base()

class Session(Base):
    """Interview session model"""
    __tablename__ = "sessions"
    
    session_id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    candidate_name = Column(String, nullable=False)
    interviewer_name = Column(String, nullable=True)
    problem_statement = Column(Text, nullable=False)
    problem_id = Column(Integer, nullable=True)  # Reference to problem in problems.db
    start_time = Column(DateTime, default=datetime.utcnow)
    end_time = Column(DateTime, nullable=True)
    status = Column(String, default="active")  # active, completed, terminated
    phase = Column(String, default="coding")  # coding, interview, completed
    submitted_at = Column(DateTime, nullable=True)  # When coding phase submitted
    session_data = Column(JSON, default=dict)  # Additional session metadata
    ai_insights = Column(JSON, nullable=True)  # Generated by Analyzer AI
    notebook_data = Column(JSON, nullable=True)  # Saved notebook cells and outputs
    
    # Relationships
    events = relationship("Event", back_populates="session", cascade="all, delete-orphan")
    ai_interactions = relationship("AIInteraction", back_populates="session", cascade="all, delete-orphan")
    features = relationship("Feature", back_populates="session", cascade="all, delete-orphan")

class Event(Base):
    """Behavioral event tracking model"""
    __tablename__ = "events"
    
    event_id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    session_id = Column(String, ForeignKey("sessions.session_id"), nullable=False)
    timestamp = Column(DateTime, default=datetime.utcnow)
    event_type = Column(String, nullable=False)  # SESSION_START, CODE_EDIT, AI_PROMPT, etc.
    event_metadata = Column(JSON, default=dict)  # Event-specific data
    sequence_number = Column(Integer, nullable=False)  # Order within session
    
    # Relationships
    session = relationship("Session", back_populates="events")

class AIInteraction(Base):
    """AI assistant interaction model"""
    __tablename__ = "ai_interactions"
    
    interaction_id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    session_id = Column(String, ForeignKey("sessions.session_id"), nullable=False)
    timestamp = Column(DateTime, default=datetime.utcnow)
    user_prompt = Column(Text, nullable=False)
    ai_response = Column(Text, nullable=False)
    intent_label = Column(String, nullable=True)  # CONCEPT_HELP, DEBUG_HELP, etc.
    response_used = Column(Boolean, default=False)  # Did candidate use the response?
    context_data = Column(JSON, default=dict)  # Code context, error context, etc.
    
    # Relationships
    session = relationship("Session", back_populates="ai_interactions")

class Feature(Base):
    """Recruiter insight features model"""
    __tablename__ = "features"
    
    feature_id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    session_id = Column(String, ForeignKey("sessions.session_id"), nullable=False)
    feature_name = Column(String, nullable=False)  # Problem Understanding, Analytical Thinking, etc.
    feature_value = Column(Float, nullable=False)  # Computed score/rating
    confidence_score = Column(Float, default=0.0)  # Confidence in the measurement
    evidence = Column(JSON, default=list)  # Supporting events/interactions
    computed_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    session = relationship("Session", back_populates="features")

# ============================================================================
# EVENT TAXONOMY
# ============================================================================
# Comprehensive event classification system for behavioral analysis
# Events are organized by category to enable structured analysis by Analyzer AI

# Event type constants - Organized by category
EVENT_TYPES = [
    # ===== SESSION LIFECYCLE EVENTS =====
    "SESSION_START",           # Interview session begins
    "SESSION_PAUSED",          # Candidate takes break
    "SESSION_RESUMED",         # Returns from break
    "PHASE_SUBMITTED",         # Submits coding phase, moves to interview
    "INTERVIEW_STARTED",       # Interview phase begins
    "SESSION_COMPLETED",       # Interview fully completed
    "SESSION_ABANDONED",       # Left without completing
    
    # ===== CODE EDITING EVENTS =====
    "CODE_EDIT",               # General code modification
    "CODE_RUN",                # Code execution attempt
    "CODE_DELETED",            # Deleted significant code
    "CODE_RESTORED",           # Undo/restore previous code
    "COMMENT_ADDED",           # Added code comment (good practice)
    "COPY_PASTE_DETECTED",     # Pasted code (possible AI copy)
    
    # ===== SQL QUERY EVENTS =====
    "SQL_RUN",                 # SQL query executed
    "QUERY_MODIFIED",          # SQL query changed
    "QUERY_OPTIMIZED",         # Query performance improved
    "QUERY_SUBMITTED",         # Final query submission
    "SYNTAX_ERROR",            # SQL syntax error
    "TABLE_JOINED",            # Used JOIN operation
    "AGGREGATE_USED",          # Used COUNT, SUM, AVG, etc.
    "SUBQUERY_USED",           # Used nested SELECT
    "GROUPING_APPLIED",        # Used GROUP BY
    "FILTER_APPLIED",          # Used WHERE clause
    "WINDOW_FUNCTION_USED",    # Advanced SQL (OVER, PARTITION BY)
    
    # ===== EXECUTION & RESULTS EVENTS =====
    "RUN_RESULT",              # Execution result received
    "ERROR_OCCURRED",          # Runtime error
    "ERROR_RESOLVED",          # Error successfully fixed
    "RESULT_VALIDATED",        # Checked if results make sense
    "RESULT_COMPARED",         # Compared multiple results
    "OUTLIER_DETECTED",        # Found unusual pattern
    "NULL_HANDLED",            # Dealt with NULL values
    
    # ===== DATA EXPLORATION EVENTS =====
    "DATA_VIEW",               # Viewed data/results
    "SCHEMA_EXPLORED",         # Clicked "Show Schema" button
    "TABLE_PREVIEWED",         # Previewed table contents
    "DATA_QUALITY_CHECKED",    # Examined data quality
    
    # ===== AI INTERACTION EVENTS =====
    "AI_PROMPT",               # Sent message to AI helper
    "AI_RESPONSE",             # Received AI response
    "AI_RESPONSE_USED",        # Applied AI suggestion
    "AI_CODE_COPIED",          # Copied AI code directly
    "AI_CODE_MODIFIED",        # Modified AI suggestion (good!)
    "AI_HINT_REQUESTED",       # Asked for hint (not full solution)
    "AI_HELP_ESCALATION",      # Repeated similar question
    "HELP_DECLINED",           # Chose not to use AI help
    
    # ===== INTERVIEW PHASE EVENTS =====
    "INTERVIEW_QUESTION",      # AI interviewer asks question
    "INTERVIEW_ANSWER",        # Candidate answers
    "INSIGHT_SHARED",          # Explained findings
    "APPROACH_EXPLAINED",      # Described methodology
    "FOLLOWUP_ANSWERED",       # Responded to follow-up
    
    # ===== PROBLEM-SOLVING PATTERN EVENTS =====
    "APPROACH_CHANGED",        # Pivoted to different solution
    "HYPOTHESIS_FORMED",       # Stated expected outcome
    "VALIDATION_ATTEMPT",      # Trying to verify correctness
    "DEAD_END_REACHED",        # Unproductive path taken
    "BREAKTHROUGH",            # Significant progress made
    "BACKTRACKED",             # Reverted to earlier approach
    
    # ===== ATTENTION & TIMING EVENTS =====
    "IDLE_GAP",                # Period of inactivity
    "FOCUS_LOST",              # Tab/window lost focus
    "FOCUS_REGAINED",          # Returned to platform
    "PAUSE_DETECTED",          # Long thinking pause (>30s)
    "RUSH_DETECTED",           # Rapid edits without testing
    "TIME_WARNING_SHOWN",      # Timer warning displayed
    
    # ===== WORKSPACE EVENTS =====
    "NOTEBOOK_CELL_ADDED",     # Created new query cell
    "NOTEBOOK_CELL_DELETED",   # Removed cell
    "CELL_REORDERED",          # Changed cell order
    "RESULT_EVALUATED",        # Assessed output quality
]

# ============================================================================
# EVENT TAXONOMY CLASSIFICATION
# ============================================================================
# Maps events to categories for structured analysis

EVENT_CATEGORIES = {
    "session_lifecycle": [
        "SESSION_START", "SESSION_PAUSED", "SESSION_RESUMED", 
        "PHASE_SUBMITTED", "INTERVIEW_STARTED", "SESSION_COMPLETED", 
        "SESSION_ABANDONED"
    ],
    "code_editing": [
        "CODE_EDIT", "CODE_RUN", "CODE_DELETED", "CODE_RESTORED",
        "COMMENT_ADDED", "COPY_PASTE_DETECTED"
    ],
    "sql_operations": [
        "SQL_RUN", "QUERY_MODIFIED", "QUERY_OPTIMIZED", "QUERY_SUBMITTED",
        "SYNTAX_ERROR", "TABLE_JOINED", "AGGREGATE_USED", "SUBQUERY_USED",
        "GROUPING_APPLIED", "FILTER_APPLIED", "WINDOW_FUNCTION_USED"
    ],
    "execution_results": [
        "RUN_RESULT", "ERROR_OCCURRED", "ERROR_RESOLVED", "RESULT_VALIDATED",
        "RESULT_COMPARED", "OUTLIER_DETECTED", "NULL_HANDLED"
    ],
    "data_exploration": [
        "DATA_VIEW", "SCHEMA_EXPLORED", "TABLE_PREVIEWED", "DATA_QUALITY_CHECKED"
    ],
    "ai_interaction": [
        "AI_PROMPT", "AI_RESPONSE", "AI_RESPONSE_USED", "AI_CODE_COPIED",
        "AI_CODE_MODIFIED", "AI_HINT_REQUESTED", "AI_HELP_ESCALATION",
        "HELP_DECLINED"
    ],
    "interview_phase": [
        "INTERVIEW_QUESTION", "INTERVIEW_ANSWER", "INSIGHT_SHARED",
        "APPROACH_EXPLAINED", "FOLLOWUP_ANSWERED"
    ],
    "problem_solving": [
        "APPROACH_CHANGED", "HYPOTHESIS_FORMED", "VALIDATION_ATTEMPT",
        "DEAD_END_REACHED", "BREAKTHROUGH", "BACKTRACKED"
    ],
    "attention_timing": [
        "IDLE_GAP", "FOCUS_LOST", "FOCUS_REGAINED", "PAUSE_DETECTED",
        "RUSH_DETECTED", "TIME_WARNING_SHOWN"
    ],
    "workspace": [
        "NOTEBOOK_CELL_ADDED", "NOTEBOOK_CELL_DELETED", "CELL_REORDERED",
        "RESULT_EVALUATED"
    ]
}

# Event criticality levels for Analyzer AI prioritization
EVENT_CRITICALITY = {
    "critical": [  # Must track for basic analysis
        "SESSION_START", "PHASE_SUBMITTED", "INTERVIEW_STARTED", 
        "SESSION_COMPLETED", "SQL_RUN", "AI_PROMPT", "AI_RESPONSE"
    ],
    "high": [  # Important for quality scoring
        "QUERY_SUBMITTED", "TABLE_JOINED", "AGGREGATE_USED", "SUBQUERY_USED",
        "ERROR_OCCURRED", "ERROR_RESOLVED", "SCHEMA_EXPLORED", "AI_RESPONSE_USED"
    ],
    "medium": [  # Useful for behavioral patterns
        "CODE_EDIT", "QUERY_MODIFIED", "APPROACH_CHANGED", "RESULT_VALIDATED",
        "INTERVIEW_ANSWER", "FOCUS_LOST", "IDLE_GAP"
    ],
    "low": [  # Nice-to-have for deep insights
        "CODE_DELETED", "PAUSE_DETECTED", "NOTEBOOK_CELL_ADDED", 
        "HELP_DECLINED", "COMMENT_ADDED"
    ]
}

# SQL complexity indicators (parsed from query text)
SQL_COMPLEXITY_MARKERS = {
    "basic": ["SELECT", "FROM", "WHERE", "LIMIT"],
    "intermediate": ["JOIN", "GROUP BY", "HAVING", "ORDER BY", "DISTINCT"],
    "advanced": ["SUBQUERY", "UNION", "CASE", "WITH", "CTE"],
    "expert": ["WINDOW FUNCTION", "PARTITION BY", "OVER", "RECURSIVE"]
}

# AI intent labels
AI_INTENT_LABELS = [
    "CONCEPT_HELP",
    "DEBUG_HELP", 
    "APPROACH_HELP",
    "VALIDATION",
    "DIRECT_SOLUTION",
    "EXPLANATION"
]

# Recruiter insight dimensions
FEATURE_DIMENSIONS = [
    "Problem Understanding",
    "Analytical Thinking",
    "Debugging Ability",
    "Independence vs AI Reliance",
    "Quality of AI Collaboration",
    "Iterative Thinking",
    "Code Quality",
    "Error Handling",
    "Data Exploration Skills",
    "Communication Clarity"
]